### PR TITLE
Add classes for hammer cli commands

### PR DESCRIPTION
**Pull request by ekohl**
This is not complete and there are more plugins, but this is a good start.

### CODE REVIEW

**Comment by mmoll** [comment]
I didn't test this, but think this doesn't work on Debian, where no underscores are allowed in package names.

**Comment by ekohl** [comment]
I pushed an updated version with acceptance tests - haven't ran them myself yet, will check when I get back home.

**Comment by mmoll** [comment]
:broken_heart: but almost there :)

**Comment by ekohl** [comment]
I do believe it should be fixed now. Let's wait to see if Travis agrees :)

**Comment by mmoll** [comment]
merged, bedankt @ekohl!

**Pull request merged**
