### PR TITLE
Add hammer plugin for foreman_webhooks

### PR DESCRIPTION
**Pull request by ofedoren**

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
Could you also add an acceptance test for it? https://github.com/theforeman/puppet-foreman/blob/master/spec/acceptance/foreman_cli_plugins_spec.rb should be the place for that.

**Comment by ofedoren** [comment]
@ekohl, I guess done...

**Comment by ekohl** [comment]
Looks like there is no package on EL8. https://github.com/theforeman/foreman-packaging/commit/b768dc04cd02034ec10dbd50b7605751e098b859 probably hasn't triggered a rebuild in koji. This is something the packaging team needs to fix.

And I guess it's not packaged at all on Debian-based distros. Do you want to address that or change the tests to only test on RPMs?

**Comment by ekohl** [comment]
> Looks like there is no package on EL8. [theforeman/foreman-packaging@b768dc0](https://github.com/theforeman/foreman-packaging/commit/b768dc04cd02034ec10dbd50b7605751e098b859) probably hasn't triggered a rebuild in koji. This is something the packaging team needs to fix.

http://koji.katello.org/koji/buildinfo?buildID=66308 exists, https://ci.theforeman.org/job/foreman-plugins-nightly-rpm-pipeline/681/ will publish it.

**Comment by ofedoren** [comment]
> And I guess it's not packaged at all on Debian-based distros. Do you want to address that or change the tests to only test on RPMs?

I'll try to setup a Debian VM in the next few days to create a PR for packaging.

**Comment by ofedoren** [comment]
@ekohl here is packaging PR for Debian: https://github.com/theforeman/foreman-packaging/pull/6952

**Comment by ekohl** [comment]
That passed, thanks!

**Comment by ofedoren** [comment]
@ekohl, as you mentioned in https://github.com/theforeman/foreman-installer/pull/702#issuecomment-892087085, what branch should I use to open a CP PR against? I need this plugin to be available for installation through installer for 2.5/6.10.

**Pull request merged**
