### PR TITLE
Refs #11681 - Explicitly use UTF-8 as postgres database encoding

### PR DESCRIPTION
**Pull request by iNecas**

### CODE REVIEW

**Comment by ekohl** [comment]
:+1: doesn't hurt to be explicit

**Comment by mmoll** [comment]
:+1: I just don't know if this can have negative impact on existing installationw with a DB in non-UTF-8?

**Comment by stbenjam** [comment]
Talked about this over in https://github.com/Katello/puppet-candlepin/pull/26#issuecomment-137556175, it's a manual process

**Comment by mmoll** [comment]
merged, díky @iNecas!
and thanks @stbenjam for clarifying

**Pull request merged**
