### PR TITLE
Improve formatting of foreman_smartproxy feature lists

### PR DESCRIPTION
**Pull request by domcleal**
Originally:

    change from ["Logs", "Puppet CA", "TFTP"] to Puppet Puppet CA TFTP Logs failed

Now:

    change from [Logs, Puppet CA, TFTP] to [Logs, Puppet, Puppet CA, TFTP] failed

### CODE REVIEW

**Comment by ekohl** [comment]
I doubt it'll happen, but is ```,``` valid in a feature name? I wonder if we should somehow restrict feature names to ```[A-Za-z0-9 _-]``` or if that'll be an annoying restriction somewhere.

**Comment by domcleal** [comment]
Yes, I think a comma would be valid in Foreman and in the Puppet type. If Foreman allows it then the type shouldn't prevent them, however to use one would certainly be unusual - these are hard-coded strings by developers rather than user editable.

I think I'm OK with the possible future ambiguity, if only to make the output more human-readable. But I can add the quotation marks back in if you'd like.

**Comment by domcleal** [comment]
PR updated with quote marks (using #inspect) around each item in the list.

**Comment by mmoll** [comment]
merged, thanks @domcleal!

**Pull request merged**
