### PR TITLE
fixes #14060 - be a little more helpful on proxy registration failure

### PR DESCRIPTION
**Pull request by stbenjam**
This is a fairly consistent problem that the error shown isn't helpful enough, and users end up wondering what went wrong.  This tries to provide at least a couple of tips.  What do you think?

### CODE REVIEW

**Comment by ekohl** [comment]
I'm somewhat surprised that it isn't showing more detail as it is now. Are we sure raise_error is even called because the messages don't match up.

**Comment by stbenjam** [comment]
Yea, it's called down below in the create/destroy methods if a failure happens. The actual error message in the bug is quite old, but I saw another user hit this the other day on IRCy and it matched the current format.

I think the text maybe needs some changes to identify the most common cases, not sure what I have is the most useful.  @ehelms mentioned on IRC there's a couple other things like foreman missing from trusted hosts.  

I'd like to show just a couple of reasons to try to be as helpful as possible.

**Comment by ekohl** [comment]
We have explicit error codes in the smart proxy (http://projects.theforeman.org/projects/foreman/wiki/ErrorCodes). Would it be an idea to use a similar error code so people can google on it (and hopefully end up on our manual). That doesn't mean we can't expand the message, but especially common errors may require a large description which won't fit in puppet.

**Comment by mmoll** [comment]
I'm a bit unsure about this. Expanding the error message is good, however, things like hostname resolving {c,sh}ould be checked beforehand (e.g. by installer hooks) and there's the fact missing that the proxy log is on the proxy host (which could be a different one). Maybe it would be sufficient to just add some URL to the message that has more information?

**Comment by stbenjam** [comment]
I like the error code idea.  What about having code similar to `::Foreman::Exception` in extlib? It might not be so nice because it'd have to be a parser function I guess.

But "ERFXX-XXXX"  googles better than "422 Unprocessable Entity"

**Comment by stbenjam** [comment]
The new RESTv3 provider delivers the full_messages from the active record errors, so this isn't needed anymore.

**Pull request closed without merging**
