### PR TITLE
derive base_url from foreman-proxy/settings.yml by default

### PR DESCRIPTION
**Pull request by jhoblitt**
Setting the base_url param on all foreman_* resource declarations isn't
very DRY (resource defaults are another option).  Deriving this value
from /etc/foreman-proxy/settings.yml is consistent with looking up
tls/oauth data in /etc/foreman/settings.yaml.

### CODE REVIEW

**Comment by jhoblitt** [comment]
rebased on current master

**Review by ehelms — APPROVED** [review]

**Comment by jhoblitt** [comment]
rebased on current master.

**Comment by jhoblitt** [comment]
rebased on current master.

**Pull request merged**
