### PR TITLE
Add support for Ubuntu 22.04

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by kenyon** [comment]
Ubuntu 22.04 is not yet supported upstream though, right? https://github.com/theforeman/theforeman.org/blob/5c0fad89a1e4ca8348ad558a6af767835589e2f7/_includes/manuals/nightly/3.1.1_supported_platforms.md

**Comment by ekohl** [comment]
This is one of the steps to get there. CI in this module verifies some packages which gives a decent baseline.

**Comment by evgeni** [comment]
@kenyon you can follow the progress at https://github.com/orgs/theforeman/projects/13

**Comment by evgeni** [comment]
:green_apple:

**Review by ekohl — APPROVED** [review]

**Pull request merged**
