### PR TITLE
fixes #11069 - add brightbox/passenger-legacy PPA for Passenger

### PR DESCRIPTION
**Pull request by domcleal**
Untested, will try to check it's all OK later.

http://projects.theforeman.org/issues/11069

### CODE REVIEW

**Comment by mmoll** [comment]
tested, makes it work again. :+1:

**Comment by ekohl** [comment]
Thanks!

**Comment by sodabrew** [comment]
These passenger packages are terribly old and not actively maintained (that's why @johnl moved them to a separate repo). I hope they aren't still in use in Foreman 1.9 and up!?

**Comment by domcleal** [comment]
@sodabrew they are if you're still using 12.04.  I'm not sure we have an alternative at the moment?

**Pull request merged**
