### PR TITLE
Test proxypass keepalive and ping

### PR DESCRIPTION
**Pull request by jturel**

### CODE REVIEW

**Comment by ekohl** [comment]
Any progress on this? Should we close it?

**Comment by jturel** [comment]
If https://community.theforeman.org/t/katello-intermittent-502-error-publishing-new-content-view-version/21531/12?u=jonathon_turel doesn't pan out then I'll close it out

**Comment by jturel** [comment]
Closing this for now as the community user got around the problem by incorporating the changes here and adding timeout=900 on their Puma proxypass.

Since they tested a few things at once but it's inconclusive what actually fixed it. Since they were seeing timeout related errors, I suspect timeout=900 was the fix.

```
httpd/foreman-ssl_error_ssl.log-20201208.gz:[Tue Dec 08 02:00:35.153018 2020] [proxy_http:error] [pid 15412] (70007)The timeout specified has expired: [client 10.10.10.10:38078] AH01102: error reading status line from remote server 127.0.0.1:3000
httpd/foreman-ssl_error_ssl.log-20201208.gz:[Tue Dec 08 02:00:35.153104 2020] [proxy:error] [pid 15412] [client 10.10.10.10:38078] AH00898: Timeout on 100-Continue returned by /katello/api/content_views/11/publish
```

I originally opened this in response to errors such as below, which the two configurations I added here might address. This can be revisited later if we get more reports.

```
foreman-ssl_error_ssl.log:[Fri Aug 21 01:16:00.879522 2020] [proxy:error] [pid 19486] (32)Broken pipe: [client 10.10.183.59:58102] AH01084: pass request body failed to 127.0.0.1:3000 (127.0.0.1)
foreman-ssl_error_ssl.log:[Fri Aug 21 01:16:00.879690 2020] [proxy_http:error] [pid 19486] [client 10.10.183.59:58102] AH01097: pass request body failed to 127.0.0.1:3000 (127.0.0.1) from 10.10.183.59 ()
```

**Comment by jturel** [comment]
Record keeping: this was the BZ I was investigating https://bugzilla.redhat.com/show_bug.cgi?id=1847784

**Pull request closed without merging**
