### PR TITLE
Fix lack of idempotency in foreman_smartproxy_host provider

### PR DESCRIPTION
**Pull request by ehelms**
@adamruzicka Could you take a look at this

I identified this over here -- https://github.com/theforeman/foreman-operations-collection/runs/4395871312?check_suite_focus=true#step:6:939

### CODE REVIEW

**Comment by evgeni** [comment]
Is that something that the CI of this repo also should catch?

**Comment by adamruzicka** [comment]
LGTM, but specs will need updating

**Comment by ehelms** [comment]
> Is that something that the CI of this repo also should catch?

I was surprised it did not originally.

**Comment by adamruzicka** [comment]
> I was surprised it did not originally.

Could it be that in CI `host['smart_proxy_id'] == host['infrastructure_facet']['smart_proxy_id']`, but not in the ops pipelines?

**Comment by ehelms** [comment]
> > Is that something that the CI of this repo also should catch?
> 
> I was surprised it did not originally.

Oh yea, cause this provider is used by puppet-foreman_proxy and so this module does not have acceptance tests for this provider.

**Comment by ehelms** [comment]
The current failures are only related to the prometheus testing, and are erroring with the following:

```
2021-12-06T14:32:38 [I|app|2f88d004] Backtrace for 'Action failed' error (NoMethodError): undefined method `increment' for nil:NilClass
 2f88d004 | /usr/share/foreman/lib/foreman/telemetry_sinks/prometheus_sink.rb:31:in `increment_counter'
 2f88d004 | /usr/share/foreman/lib/foreman/telemetry.rb:126:in `block in increment_counter'
 2f88d004 | /usr/share/foreman/lib/foreman/telemetry.rb:126:in `each'
 2f88d004 | /usr/share/foreman/lib/foreman/telemetry.rb:126:in `increment_counter'
 2f88d004 | /usr/share/foreman/lib/foreman/telemetry.rb:79:in `block in register_rails'
```

Tracked here https://projects.theforeman.org/issues/34096

**Comment by ehelms** [comment]
@adamruzicka @evgeni y'all good with thi snow?

**Comment by adamruzicka** [comment]
Yup, as far as I can tell this is the way it should be

**Review by evgeni — APPROVED** [review]

**Pull request merged**
