### PR TITLE
Use puppetlabs-apache keepalive options

### PR DESCRIPTION
**Pull request by ekohl**
https://github.com/puppetlabs/puppetlabs-apache/commit/192d89427ade170a9c76fc0df0bcda0786c0cb53
added support for this so we can remove our custom fragment.

### CODE REVIEW

**Comment by ekohl** [comment]
I haven't had time to test this yet.

**Comment by domcleal** [comment]
There will be some failures with fragment testing in spec/classes/foreman_config_passenger_spec.rb, plus the HTTP vhost further up passenger.pp needs to have the template fragment replaced too.

**Comment by ekohl** [comment]
I cancelled the build since we know the tests will fail.

**Comment by ekohl** [comment]
Updated

**Comment by mmoll** [comment]
merged, bedankt @ekohl!

**Pull request merged**
