### PR TITLE
plugins:ansible - Initial Ansible support

### PR DESCRIPTION
**Pull request by dLobatog**

### CODE REVIEW

**Comment by mmoll** [comment]
:+1:

**Comment by dLobatog** [comment]
If I made the plugin optionally install Ansible as well, how likely to be accepted would it be? I think it'd be useful because:

* The smart-proxy-ansible plugin (to run remote execution) needs Ansible the executable with the proper Foreman callback. 
* Deploying the callback (a python script) and configuring /etc/ansible.cfg so people don't have to would make it easier.

**Comment by mmoll** [comment]
I would need to delve a bit more into how the connection between Foreman, Foreman-Proxy and Ansible is made. For Salt and Chef, the **proxy** plugin packages depend onto their respective master's package and both have support in puppet-foreman_proxy to configure their integration config files. Would this touch puppet-foreman for Ansible?

**Comment by dLobatog** [comment]
@mmoll Don't worry about proxy at all now - foreman_ansible itself doesn't need the proxy for anything yet. At least until https://github.com/theforeman/foreman_remote_execution/pull/134 is merged we don't have to worry about that bit.

**Comment by mmoll** [comment]
allright.

**Comment by mmoll** [comment]
@dLobatog can you please rebase onto current master, so all tests are green again?

As this is installing the foreman core plugin and other configurations have to be handled elsewhere, this is good to go, IMHO.

**Comment by dLobatog** [comment]
Updated!

**Comment by mmoll** [comment]
merged, gracias @dLobatog!

**Pull request closed without merging**
