### PR TITLE
Write websockets_encrypt as on/off instead of a bool

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by mmoll** [comment]
:+1: no idea about the Puppet 2.7 + Ruby 1.8 test error...

**Comment by ekohl** [comment]
Added 2 commits that should update the tests a bit. Maybe they help.

**Comment by ekohl** [comment]
Test failures on puppet 2.7 are now due to the unless keyword in puppetlabs-apt. I think we should pin that as well.

**Comment by mmoll** [comment]
merged, thanks @ekohl!

**Pull request merged**
