### PR TITLE
[WIP] Add additional testing using stricter settings

### PR DESCRIPTION
**Pull request by ekohl**
This should replace https://github.com/theforeman/puppet-foreman/pull/182.

### CODE REVIEW

**Comment by ekohl** [comment]
Just testing if travis picks it up and how many tests fail.

**Comment by mmoll** [comment]
needs a rebase ;)

**Comment by ekohl** [comment]
Let's see how badly our tests fail now :)

**Comment by mmoll** [comment]
should be covered by the Puppet 4 tests now?

**Comment by domcleal** [comment]
I don't think Puppet 4 shipped with strict variables enabled in the end.

**Comment by mmoll** [comment]
I guess this can get closed for now?

**Comment by ekohl** [comment]
Yes, that's fine.

**Pull request closed without merging**
