### PR TITLE
fixes #14127 - turn on httpd server-status scoreboard

### PR DESCRIPTION
**Pull request by komidore64**

### CODE REVIEW

**Comment by ekohl** [comment]
I don't think we want to force this on all our users. I can see this being useful for many of them, but I think it belongs in the profile layer. Not sure where to place that with the installer though.

**Comment by komidore64** [comment]
What do you mean by "profile layer?"

**Comment by domcleal** [comment]
A higher level class, i.e. http://www.craigdunn.org/2012/05/239/.

**Comment by ekohl** [comment]
Given we don't want to manage Apache in our modules I'm closing this. A possible solution for this might be https://github.com/theforeman/foreman-installer/pull/204

**Pull request closed without merging**
