### PR TITLE
Quietly ignore missing ruby-augeas library

### PR DESCRIPTION
**Pull request by domcleal**
Closes GH-283

### CODE REVIEW

**Comment by ekohl** [comment]
:+1:

**Comment by mmoll** [comment]
I can't really test... @genebean maybe?
:+1: anyway

**Comment by mmoll** [comment]
merged as  5e6f1fc, thanks @domcleal!

**Comment by genebean** [comment]
Sorry I couldn't get in yesterday to help test this!

**Comment by mmoll** [comment]
@genebean no worries :)

**Pull request closed without merging**
