### PR TITLE
Use rspec-puppet-facts where possible

### PR DESCRIPTION
**Pull request by ekohl**
This is pulled from https://github.com/theforeman/puppet-foreman/pull/332 and should be in a mergeable state.

### CODE REVIEW

**Comment by mmoll** [comment]
the newly added rubyversion fact related things are easy... but the 2h limit is striking again :disappointed:

**Comment by ekohl** [comment]
I increased coverage on many tests so the 2h limit actually hit more configs. I think we should use the pattern created in https://github.com/theforeman/puppet-puppet/pull/318 to limit testing so many OS'es.

**Comment by mmoll** [comment]
The modulesync branch got merged :smiley:

**Comment by ekohl** [comment]
Rebased and added skipping code.

**Comment by mmoll** [comment]
this needs another rebase and maybe a slight tush-up regarding the rubyversion fact, but LGTM :100:

**Comment by ekohl** [comment]
Rebased, but untested.

**Comment by mmoll** [comment]
the following should resolve the remaing error:
```diff
diff --git a/spec/classes/foreman_puppetmaster_spec.rb b/spec/classes/foreman_puppetmaster_spec.rb
index 690e3fa..09e414b 100644
--- a/spec/classes/foreman_puppetmaster_spec.rb
+++ b/spec/classes/foreman_puppetmaster_spec.rb
@@ -6,10 +6,19 @@ describe 'foreman::puppetmaster' do
     next if exclude_test_os() and exclude_test_os.include?(os)
 
     context "on #{os}" do
-      let :facts do
-        facts.merge({
-          :concat_basedir => '/tmp',
-        })
+      if facts[:osfamily] == 'RedHat' and facts[:operatingsystemmajrelease] == '6'
+        let :facts do
+          facts.merge({
+            :concat_basedir => '/tmp',
+            :rubyversion    => '1.8.7',
+          })
+        end
+      else
+        let :facts do
+          facts.merge({
+            :concat_basedir => '/tmp',
+          })
+        end
       end
 
       describe 'without custom parameters' do
```
Maybe this can written in a smarter way :bulb:

**Comment by mmoll** [comment]
Another thing, found while testing under Puppet 4:
```diff
diff --git a/spec/defines/foreman_install_repos_spec.rb b/spec/defines/foreman_install_repos_spec.rb
index 1615c38..4a021db 100644
--- a/spec/defines/foreman_install_repos_spec.rb
+++ b/spec/defines/foreman_install_repos_spec.rb
@@ -43,6 +43,7 @@ describe 'foreman::install::repos' do
         :operatingsystem        => 'Amazon',
         :operatingsystemrelease => '6.4',
         :osfamily               => 'Linux',
+        :rubyversion            => '1.8.7',
       }
     end
```

**Comment by domcleal** [comment]
@mmoll do you want to add that into this branch and we can merge this?  Otherwise it all looks in good order to me.

**Comment by mmoll** [comment]
You could cherry-pick 0071123 and 32746e9 from the `puppet-4` branch.

**Comment by domcleal** [comment]
Ah sorry, I thought this was on theforeman, I just noticed that it's @ekohl's.

**Comment by mmoll** [comment]
alternatively you could review and merge the puppet-4 branch in #332 ;)

**Comment by domcleal** [comment]
Yeah, thought I'd try and break the problem down a bit!  But in actual fact, the extra commits in 332 aren't that bad.

**Comment by ekohl** [comment]
When I started my intention was to first merge this and then rebase the puppet-4 branch onto it.

**Comment by domcleal** [comment]
I'm fine with either at the moment, but would marginally prefer merging this (with @mmoll's patches) just to be able to look at the puppet-4 PR with a smaller diff, so it may be worth you updating it.

**Comment by mmoll** [comment]
I have no problem with either way, so let's get this here in first :)

**Comment by mmoll** [comment]
the path diffs in the tftp/discovery tests seem to happen also in the master branch, so this seems good to go for me :+1:

**Comment by domcleal** [comment]
Merged, thanks all!

**Pull request merged**
