### PR TITLE
add ExportCertData option needed by #12127

### PR DESCRIPTION
**Pull request by timogoebel**
This PR exports the client certificate to the rails env, needed by http://projects.theforeman.org/issues/12127

### CODE REVIEW

**Comment by domcleal** [comment]
:+1:

**Comment by timogoebel** [comment]
Tests fail for 1.8.7/ Puppet 3.5, but this looks like a travis issue.

```
Your test run exceeded 120 minutes. 
```

**Comment by domcleal** [comment]
Yep, it's a known problem - sorry for the false positive, we'll just ignore it.

**Comment by mmoll** [comment]
Shouldn't do any harm when not using the exported data, so merged. Danke @timogoebel!

**Pull request merged**
