### PR TITLE
support plugin foreman_expire_hosts

### PR DESCRIPTION
**Pull request by timogoebel**

### CODE REVIEW

**Comment by ekohl** [comment]
:+1: on passing tests.

**Comment by domcleal** [comment]
Merged, thanks @timogoebel!

**Comment by domcleal** [comment]
If you could also send a PR over to foreman-installer which adds the new class to config/ and a config migration file, it'll show up in the installer itself then.

**Comment by timogoebel** [comment]
It's on my todo list, @domcleal . Thanks for reminding me, though.

**Pull request closed without merging**
