### PR TITLE
Refactor f::config::passenger to f::config::apache

### PR DESCRIPTION
**Pull request by ekohl**
Also uses some functions from stdlib to clean up code.

### CODE REVIEW

**Comment by mmoll** [comment]
@ekohl tests need updating?

**Comment by ehelms** [comment]
Will this break modules we manage ?

**Comment by ekohl** [comment]
This is designed as non-breaking by keeping the deprecated defines in place. We should be updating them so we can actually drop them if we prepare PRs.

**Comment by mmoll** [comment]
merged bedankt @ekohl!

**Pull request merged**
