### PR TITLE
Fixes #21023 - Update start-timeout to 90

### PR DESCRIPTION
**Pull request by chris1984**

### CODE REVIEW

**Comment by chris1984** [comment]
@ekohl can I get a review, please?

**Comment by ekohl** [comment]
My understanding the new plan was to lower the 600 second waiting of passenger to 90 so it matches the systemd default. @ehelms?

**Comment by ehelms** [comment]
Yep.

**Comment by chris1984** [comment]
@ekohl can I get another review of this please?

**Comment by ekohl** [comment]
@chris1984 see https://www.traviscistatus.com/incidents/v4jnp6nkgzqx for the docker timeout.

**Comment by chris1984** [comment]
[test]

**Comment by chris1984** [comment]
@ekohl tests are passing now, can I get a merge please?

**Comment by mmoll** [comment]
merged, thanks @chris1984!

**Pull request merged**
