### PR TITLE
allow the configuration of serveraliases

### PR DESCRIPTION
**Pull request by mmoll**
In some environments, foreman might have a different name to different
networks. Different implementations of SSL (jruby, curl-tls, openssl),
appear to have different levels of tolerance for such a certificate
(mis)configuration in Apache httpd's vhost.

@igalic As we will release a new module version soon, I took the liberty to take your change and adapt it to current master in hope to get it in before the release.

### CODE REVIEW

**Comment by ekohl** [comment]
:+1: on green tests.

**Comment by mmoll** [comment]
travis had some hickups, now it's :green_heart:

**Comment by domcleal** [comment]
Merged, thanks @igalic and @mmoll.

**Comment by igalic** [comment]
thanks everyone \o/
(sorry for vanishing._.)

**Pull request closed without merging**
