### PR TITLE
remove references to ruby193-* packages

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
Finally someone who takes the time to appreciate a good branch name :)

**Comment by ohadlevy** [comment]
> Finally someone who takes the time to appreciate a good branch name :)

is that in German? ;)

**Comment by evgeni** [comment]
I'd say the travis failures are  unrelated

**Comment by ekohl** [comment]
Yes, I need to figure out why the journald logger is broken on EL7. It used to work and may indicate an actual regression.

**Pull request merged**
