### PR TITLE
Organize Foreman parameters into logical groups

### PR DESCRIPTION
**Pull request by ehelms**
Adds additional groupings of parameters into logical groups and reduces
the scope of the "basic" parameters to the most pertinent for default
install of Foreman. This has the benefit to wrapper projects like
Kafo that parameters can be treated in groups for input and display
purposes.

This is my attempt to organize and feedback is welcome on categories. 

I debated adding an 'Initialization parameters:' grouping for all of the `initial_` parameters.

### CODE REVIEW

**Comment by ekohl** [comment]
I think this will suffer from https://projects.theforeman.org/issues/29788.

**Comment by ehelms** [comment]
It will suffer from it, however, the more I look at how we think about Kafo options and presenting the user, I'm not sure that's a bad thing anymore. We present way too much to users due to not being grouped. This introduces a pattern of:

 1) If a parameter is important to a user to config, it should be not grouped and top level
 2) If a parameter has a sane default and only more adanced use cases may want to configure it, it should be in a group and therefore will only show up for kafo using `--full-help`

If we prefer to group *all* items, then in Kafo I think we have to go with a design model where we specify what groups are "basic" and which are "advanced".

**Comment by ekohl** [comment]
How I used to think it worked as `$group` would show up in `--help` and `Advanced $group` would show up in `--full-help`. I think that still makes sense. So then we can say that `Database parameters` would be a common operation and show in in `--help` but `Deployment parameters` should be `Advanced deployment parameters` because they're not commonly changed. I think that gives a nice balance between the two.

**Comment by ehelms** [comment]
Do you know if it is possible to do sub-groups within groups?

**Comment by ekohl** [comment]
https://github.com/theforeman/kafo_parsers#rdoc-syntax doesn't mention it, but RDoc does have it built in. When thinking about the interactive mode, I wonder if you want to apply the same nesting then.

I know that in https://github.com/theforeman/puppet-puppet we are reasonably close to this kind of structure (common, agent, advanced agent, server, advanced server). Perhaps that's also a good module to play around with to see the differences.

**Comment by ehelms** [comment]
Honestly, I'd almost rather a module, or class in a module, define and group the parameters however they want. Then in Kafo, treat every parameter was an advanced parameter that lands under `--full-help` with a "basic options" list that shows options defined within that list under `--help`. This removes the friction between the installer and modules and how parameters are defined and let's the installer, which is a different experience, customize what and how it presents parameters at a scenario level.

**Comment by ekohl** [comment]
I have also thought about separating it. For what it's worth, I opened https://tickets.puppetlabs.com/browse/PDOC-267 so we could move away from RDoc to just puppet-strings syntax. An alternative is to have a separate kafo.yaml file that groups parameters. However, such a thing is a large change in how we parse it so we shouldn't take it lightly.

**Pull request closed without merging**
