### PR TITLE
Initial AzureRM support

### PR DESCRIPTION
**Pull request by apuntamb**
In reference with [foreman-installer/405](https://github.com/theforeman/foreman-installer/pull/405).

### CODE REVIEW

**Comment by apuntamb** [comment]
@tbrisker any update?

**Comment by tbrisker** [comment]
the build seems to still be failing, i know @ekohl was looking into it as it isn't related to this PR but i don't know if there's been any progress (or if we can merge this with red build)

**Comment by apuntamb** [comment]
Sure @tbrisker .
@ekohl Could you please take a look?

**Comment by evgeni** [comment]
yeah, 1.24 only, we didn't backport the packages further

**Pull request merged**
