### PR TITLE
Fix syntax warnings

### PR DESCRIPTION
**Pull request by mateusz-gozdek-sociomantic**

### CODE REVIEW

**Comment by mmoll** [comment]
could you please include #569 in this?

**Comment by mateusz-gozdek-sociomantic** [comment]
Sure. Just for the record, I decided not to, as #569 is only cosmetic fix and this actually touches the code.

**Comment by mmoll** [comment]
merged, dzięki @mateusz-gozdek-sociomantic!

**Comment by mateusz-gozdek-sociomantic** [comment]
nie ma za co :)

**Pull request merged**
