### PR TITLE
14.0.1 cherry picks

### PR DESCRIPTION
**Pull request by ekohl**
This fixes repository handling for 2.0 and beyond. To test this easily, some acceptance tests are also cherry picked. It also marks it compatible with extlib 5.0.

### CODE REVIEW

**Comment by mmoll** [comment]
The test failure seems consistent, but maybe something just broke over time in a combination that wasn't tested before... :thinking:

**Comment by wbclark** [comment]
I can reproduce the same issue locally:

`$ BEAKER_HYPERVISOR=vagrant_libvirt BEAKER_provision=yes BEAKER_destroy=onpass BEAKER_setfile=centos7-64 bundle exec rspec spec/acceptance/foreman_reverse_proxy_spec.rb`

I observe the same failures as seen on Travis.

Checking the logs for foreman.service I observe looping restarts:

```
-- Logs begin at Tue 2020-04-28 15:54:35 UTC, end at Tue 2020-04-28 16:06:56 UTC. --
Apr 28 15:59:46 centos7-64-1 systemd[1]: Started Foreman.
Apr 28 16:00:01 centos7-64-1 foreman[10005]: => Booting Puma
Apr 28 16:00:01 centos7-64-1 foreman[10005]: => Rails 5.2.1 application starting in production
Apr 28 16:00:01 centos7-64-1 foreman[10005]: => Run `rails server -h` for more startup options
Apr 28 16:00:01 centos7-64-1 foreman[10005]: Apipie cache enabled but not present yet. Run apipie:cache rake task to speed up API calls.
Apr 28 16:00:10 centos7-64-1 foreman[10005]: [10005] Puma starting in cluster mode...
Apr 28 16:00:10 centos7-64-1 foreman[10005]: [10005] * Version 4.3.3 (ruby 2.5.5-p157), codename: Mysterious Traveller
Apr 28 16:00:10 centos7-64-1 foreman[10005]: [10005] * Min threads: 0, max threads: 16
Apr 28 16:00:10 centos7-64-1 foreman[10005]: [10005] * Environment: production
Apr 28 16:00:10 centos7-64-1 foreman[10005]: [10005] * Process workers: 2
Apr 28 16:00:10 centos7-64-1 foreman[10005]: [10005] * Phased restart available
Apr 28 16:00:10 centos7-64-1 foreman[10005]: Exiting
Apr 28 16:00:10 centos7-64-1 foreman[10005]: /opt/theforeman/tfm/root/usr/share/gems/gems/puma-4.3.3/lib/puma/binder.rb:229:in `initialize': Address already in use - bind(2) for "127.0.0.1" port 3000 (Errno::EAD
Apr 28 16:00:10 centos7-64-1 foreman[10005]: from /opt/theforeman/tfm/root/usr/share/gems/gems/puma-4.3.3/lib/puma/binder.rb:229:in `new'
Apr 28 16:00:10 centos7-64-1 foreman[10005]: from /opt/theforeman/tfm/root/usr/share/gems/gems/puma-4.3.3/lib/puma/binder.rb:229:in `add_tcp_listener'
Apr 28 16:00:10 centos7-64-1 foreman[10005]: from /opt/theforeman/tfm/root/usr/share/gems/gems/puma-4.3.3/lib/puma/binder.rb:106:in `block in parse'
Apr 28 16:00:10 centos7-64-1 foreman[10005]: from /opt/theforeman/tfm/root/usr/share/gems/gems/puma-4.3.3/lib/puma/binder.rb:90:in `each'
Apr 28 16:00:10 centos7-64-1 foreman[10005]: from /opt/theforeman/tfm/root/usr/share/gems/gems/puma-4.3.3/lib/puma/binder.rb:90:in `parse'
Apr 28 16:00:10 centos7-64-1 foreman[10005]: from /opt/theforeman/tfm/root/usr/share/gems/gems/puma-4.3.3/lib/puma/cluster.rb:436:in `run'
Apr 28 16:00:10 centos7-64-1 foreman[10005]: from /opt/theforeman/tfm/root/usr/share/gems/gems/puma-4.3.3/lib/puma/launcher.rb:172:in `run'
Apr 28 16:00:10 centos7-64-1 foreman[10005]: from /opt/theforeman/tfm/root/usr/share/gems/gems/puma-4.3.3/lib/rack/handler/puma.rb:73:in `run'
Apr 28 16:00:10 centos7-64-1 foreman[10005]: from /opt/theforeman/tfm/root/usr/share/gems/gems/rack-2.1.1/lib/rack/server.rb:329:in `start'
Apr 28 16:00:10 centos7-64-1 foreman[10005]: from /opt/theforeman/tfm/root/usr/share/gems/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:53:in `start'
Apr 28 16:00:10 centos7-64-1 foreman[10005]: from /opt/theforeman/tfm/root/usr/share/gems/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:147:in `block in perform'
Apr 28 16:00:10 centos7-64-1 foreman[10005]: from /opt/theforeman/tfm/root/usr/share/gems/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:142:in `tap'
Apr 28 16:00:10 centos7-64-1 foreman[10005]: from /opt/theforeman/tfm/root/usr/share/gems/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:142:in `perform'
Apr 28 16:00:10 centos7-64-1 foreman[10005]: from /opt/theforeman/tfm/root/usr/share/gems/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
Apr 28 16:00:10 centos7-64-1 foreman[10005]: from /opt/theforeman/tfm/root/usr/share/gems/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
Apr 28 16:00:10 centos7-64-1 foreman[10005]: from /opt/theforeman/tfm/root/usr/share/gems/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
Apr 28 16:00:10 centos7-64-1 foreman[10005]: from /opt/theforeman/tfm/root/usr/share/gems/gems/railties-5.2.1/lib/rails/command/base.rb:65:in `perform'
Apr 28 16:00:10 centos7-64-1 foreman[10005]: from /opt/theforeman/tfm/root/usr/share/gems/gems/railties-5.2.1/lib/rails/command.rb:46:in `invoke'
Apr 28 16:00:10 centos7-64-1 foreman[10005]: from /opt/theforeman/tfm/root/usr/share/gems/gems/railties-5.2.1/lib/rails/commands.rb:18:in `<top (required)>'
Apr 28 16:00:10 centos7-64-1 foreman[10005]: from /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:135:in `require'
Apr 28 16:00:10 centos7-64-1 foreman[10005]: from /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
Apr 28 16:00:10 centos7-64-1 foreman[10005]: from /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:39:in `require'
Apr 28 16:00:10 centos7-64-1 foreman[10005]: from /usr/share/foreman/bin/rails:9:in `<main>'
Apr 28 16:00:10 centos7-64-1 systemd[1]: foreman.service: main process exited, code=exited, status=1/FAILURE
Apr 28 16:00:10 centos7-64-1 systemd[1]: Unit foreman.service entered failed state.
Apr 28 16:00:10 centos7-64-1 systemd[1]: foreman.service failed.
Apr 28 16:01:27 centos7-64-1 systemd[1]: Started Foreman.
Apr 28 16:01:33 centos7-64-1 foreman[10730]: => Booting Puma
```

**Comment by mmoll** [comment]
> Checking the logs for foreman.service I observe looping restarts

Maybe just adding stopping the service to the cleanup fixes this?

**Comment by mmoll** [comment]
Not 100% sure, but stopping that could also be part of a package deinstall (in the future)...

**Comment by ekohl** [comment]
> Not 100% sure, but stopping that could also be part of a package deinstall (in the future)...

It also happens if you only run the reverse proxy scenario

**Comment by ekohl** [comment]
So the issue appears to be that it's installing the nightly repo which this module is indeed incompatible with. The problem is that in master the file was removed, so the chery pick commit fcebaf2b76f5b76512a77ad6412189bb18ceaa9e didn't update it. Fixing.

**Comment by mmoll** [comment]
merged, bedankt @ekohl!

**Pull request merged**
