### PR TITLE
Fixes #19550 - support smart card certificates

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ekohl** [comment]
The code looks correct but I'm unable to test it since I don't have a smart card.

**Comment by mmoll** [comment]
same here

**Comment by ares** [comment]
I asked the reporter whether they could test it. I at least verified that the installer adds this correctly to vhost and apache2 starts. When I get some update from reporter, I'll update this PR. In worst case scenario, if it does not work, it should not do any harm...

**Comment by ares** [comment]
User confirms it works for them (see https://bugzilla.redhat.com/show_bug.cgi?id=1449088)

**Comment by mmoll** [comment]
merged, díky @ares!

**Pull request merged**
