### PR TITLE
Notify the puppet server when changing foreman.rb

### PR DESCRIPTION
**Pull request by ekohl**
Closes GH-161

I just noticed I pushed it to the wrong repository ...

### CODE REVIEW

**Comment by mmoll** [comment]
this doesn't work with passenger.

**Comment by ekohl** [comment]
I think we should solve that in the puppet-puppet module. @domcleal any opinion?

**Comment by ekohl** [comment]
@mmoll submitted another PR to take care of the passenger part.

**Comment by domcleal** [comment]
Do we need to worry about people using this class without our 'puppet' module?

**Comment by ekohl** [comment]
We already have requires later in the class so I don't think we should worry.

**Comment by domcleal** [comment]
Ah yes!

**Comment by domcleal** [comment]
Merged, thanks @ekohl!  We'll continue to work on the puppet-puppet part.

**Pull request closed without merging**
