### PR TITLE
allow newer versions of dependencies

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by ehelms** [comment]
Seeing error with  puppet module install puppetlabs-postgresql -v 6.0.0

**Comment by mmoll** [comment]
This needs a new puppetlabs-postgresql release.

**Comment by ehelms** [comment]
That's gonna be a tough one to get -- @evgeni helped us get the last one

**Comment by evgeni** [comment]
There is a community slack where you can ask for support for these modules -- and also for a release. I'll have to search the name.

**Comment by evgeni** [comment]
See https://mobile.twitter.com/dev_el_ops/status/1103263517900193792

**Comment by ekohl** [comment]
https://github.com/puppetlabs/puppetlabs-postgresql/pull/1082

**Comment by mmoll** [comment]
test failures now unrelated :green_heart:

**Pull request merged**
