### PR TITLE
Support for enabling webpack in development environments

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by ekohl** [comment]
I'm not sure I see the need for this. In puppet-katello_devel doesn't use this, right: https://github.com/theforeman/puppet-katello_devel/blob/b7e9853ac24d8ca9e1c06acb72aecbf3f8b141f8/manifests/config.pp#L4-L10

**Comment by stbenjam** [comment]
Ugh, fail. I assumed it did, I don't know why. I wish katello_devel didn't do things like that.  It's a much larger problem to solve to get puppet-foreman to deploy a dev environment, so I'll just close this.

**Comment by ehelms** [comment]
We built it that way originally because we were told that base puppet modules wouldn't accept development related configurations and thus better to write a module that handled all of it.

**Comment by stbenjam** [comment]
Oh sorry, I didn't mean that as a criticism, I know why :-) puppet-foreman supports changing the $app_root away from /usr/share, and even sqlite (for foreman-only install).  It might be possible now or close to be able to re-use it for a dev install.

**Comment by stbenjam** [comment]
Or maybe not https://github.com/theforeman/puppet-foreman/commit/afa2392fa1fd1a393345bcae4b58ae7f57c44222

**Comment by ehelms** [comment]
@stbenjam I thwarted you! Could make sense to allow that code to define multiple databases as a general practice.

**Pull request closed without merging**
