### PR TITLE
Update to puppetlabs-apache 1.2.0

### PR DESCRIPTION
**Pull request by domcleal**
Untested at the moment, will continue soon and do the same for puppet-puppet.

### CODE REVIEW

**Comment by mmoll** [comment]
:+1: works on Debian/wheezy and with the PRs I submitted to puppetlabs also with Debian/jessie (Apache 2.4). For the Puppet vhost ```SSLCARevocationCheck chain``` should be set (according to the docs, it will simply be ignored by the module for Apache <2.4), maybe also for Foreman?

**Comment by domcleal** [comment]
Thanks for testing, I'll rebase it soon and we can get it in.  I set the SSLCARevocationCheck parameter here: https://github.com/theforeman/puppet-foreman/pull/261/files#diff-b0704782a99cc0054caffb0fab302b16R158

(This module is only for Foreman, I think I have another branch in progress for puppet-puppet.)

**Comment by mmoll** [comment]
Hm, I'll test it again on fresh CentOS 7 after rebase, maybe something was saved in the answers file...

**Comment by domcleal** [comment]
Rebased.

**Comment by domcleal** [comment]
I've now tested on EL7, deleted my answers file, yum reinstalled foreman-installer and it seemed to add `SSLCARevocationCheck    "chain"` just fine to the Foreman vhost (Puppet'll be separate).

**Comment by ekohl** [comment]
:+1:

**Comment by mmoll** [comment]
Working fine on CentOS/7 and Debian/wheezy.
Thanks! :white_check_mark:

**Pull request merged**
