### PR TITLE
Fixes #14520 - remove openscap custom repo option

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by domcleal** [comment]
You may want to amend the commit message, it should say that it removes the parameter.

**Comment by ekohl** [comment]
Due to #426 there is now a merge conflict. Otherwise :+1: for when we release 6.0.0.

**Comment by mmoll** [comment]
@ares please rebase, maybe also mention in the commit message it's about openscap, as I was a bit surprised when reading the message first. :)

**Comment by ares** [comment]
@mmoll done

**Comment by ares** [comment]
I updated the metadata to 6.0.0

**Comment by mmoll** [comment]
merged, díky @ares!

**Pull request merged**
