### PR TITLE
allow the configuration of serveraliases

### PR DESCRIPTION
**Pull request by igalic**
In some environments, foreman might have a different name to different
networks. Different implementations of SSL (jruby, curl-tls, openssl),
appear to have different levels of tolerance for such a certificate
(mis)configuration in Apache httpd's vhost.

this is a rebase of #337 against the stable-5.0 branch

### CODE REVIEW

**Comment by mmoll** [comment]
@igalic this is looking good. However, please direct PRs into the master branch, thanks!

**Comment by igalic** [comment]
@mmoll you think chances of travis being happy with this will be better when i base it off master?

**Comment by mmoll** [comment]
@igalic Probably. I think 5.0 still has the monkey-patching against older rspec-puppet versions in (you'll run into #396 for sure, but that's known). Anyway, we always push to master first and would only backport if really needed.

**Comment by mmoll** [comment]
see #401

**Pull request closed without merging**
