### PR TITLE
Release 18.2.0

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
I just realized https://github.com/theforeman/puppet-foreman/pull/981 wasn't merged yet. It was red and I rebased it. Thoughts about including it?

Otherwise :+1:

**Comment by ehelms** [comment]
> I just realized #981 wasn't merged yet. It was red and I rebased it. Thoughts about including it?

Sure, I will await for it and update this

**Comment by wbclark** [comment]
Could we get https://github.com/theforeman/puppet-foreman/pull/988 in as well for this?

**Comment by ekohl** [comment]
Looks like #981 needs more work, let's not wait for it.

**Comment by wbclark** [comment]
Merged #988 .

@ehelms could you please update this? Thank you.

**Pull request merged**
