### PR TITLE
Refs #34505 - Add hammer plugin for foreman_host_reports

### PR DESCRIPTION
**Pull request by ofedoren**

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
This looks correct, but it's failing on installing the packages. Blocked on https://github.com/theforeman/foreman-packaging/pull/7618 & https://github.com/theforeman/foreman-packaging/pull/7620

**Comment by ekohl** [comment]
Looks like it hasn't been published yet:
```
        	Error: /Stage[main]/Foreman::Cli::Host_reports/Foreman::Cli::Plugin[foreman_host_reports]/Package[ruby-hammer-cli-foreman-host-reports]/ensure: change from 'purged' to 'present' failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install ruby-hammer-cli-foreman-host-reports' returned 100: Reading package lists...
```

**Comment by ofedoren** [comment]
Is there anything needed from my side to help with?

**Comment by ekohl** [comment]
Not right now, I think there's a problem with publishing Debian packages.

**Comment by ekohl** [comment]
Currently blocked on #1034. I expect that to pass, so you can rebase on top of it already if you want.

**Comment by ofedoren** [comment]
@ekohl, I've rebased, but Ubuntu still seems to fail.

**Comment by ekohl** [comment]
Yes, sadly those were some pre-existing problems. That shouldn't block.

**Pull request merged**
